name: main
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install mkdocs
        run: pip install mkdocs
      - name: deploy
        run: mkdocs gh-deploy
